# Generated by Django 5.1 on 2024-09-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("languages_spoken", models.CharField(max_length=250)),
                ("languages_to_learn", models.CharField(max_length=250)),
                ("hobbies", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=50)),
                ("category", models.CharField(max_length=50)),
                ("date", models.DateField(max_length=50)),
                ("time", models.TimeField(max_length=50)),
                ("description", models.TextField(max_length=500)),
                (
                    "participants",
                    models.ManyToManyField(related_name="events", to="app.user"),
                ),
            ],
        ),
    ]
